// <auto-generated />
namespace TEST.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_table_person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_table_person));
        
        string IMigrationMetadata.Id
        {
            get { return "202110020854544_update_table_person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
